version: '3.8'

services:
  app:
    container_name: backend
    build: ./backend/app
    working_dir: /usr/src
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

    # restart: on-failure
    volumes:
      - ./backend:/usr/src
      - storage_volume:/usr/app/files
    ports:
      - 8002:8000
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASE: ${REDIS_DATABASE}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SWAP_ROUTER: ${SWAP_ROUTER}
      ADMIN_WALLET: ${ADMIN_WALLET}
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: database
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    ports:
      - '8001:80'
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    depends_on:
      - db

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
  storage_volume:
